[versions]
spring-boot = "3.5.6"
spring-dependency-management = "1.1.7"
spotless = "8.0.0"
spotbugs = "6.4.2"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
spotless =  { id = "com.diffplug.spotless", version.ref = "spotless" }
spotbugs =  { id = "com.github.spotbugs", version.ref = "spotbugs" }
