spring:
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sandbox
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      data-source-properties:
        rewrite-batched-inserts: true
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        batch_size: 5000
      order_inserts: true
      order_updates: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
flight-delay:
  filepath: C:\Users\kvint\Downloads\flight_data_2024.csv
templates:
  dir: "src/main/resources/templates"
proxy:
  host: ${PROXY_HOST}
  port: ${PROXY_PORT}
  user: ${PROXY_USER}
  password: ${PROXY_PASSWORD}
network:
  use-okhttp: true
  throttle:
    base-millis: 500
    extra-millis: 2500